[wokwi]
version = 1
elf = ".pio/build/esp32AIThinker_sim/OpenIris-v1.10.1-esp32AIThinker_sim-46d197d-master.elf"
firmware = ".pio/build/esp32AIThinker_sim/OpenIris-v1.10.1-esp32AIThinker_sim-46d197d-master.bin"
[[net.forward]]
from = "localhost:8180"
to = "target:80"
